---
title: testDebuggingPanel
runtime: shiny
---

```{r makeDebuggingPanelOutput, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
invisible(require(shiny, quietly = T, warn.conflicts = FALSE) )
invisible(require(shinyjs, quietly = T, warn.conflicts = FALSE) )
invisible(require(shinyDebuggingPanel, quietly = T) )
invisible(require(knitr, quietly = T) )
shinyjs::useShinyjs(rmd = TRUE)

shiny::addResourcePath("shinyjs", system.file("srcjs", package = "shinyjs"))
```

```{r c1}
  observeEvent(input$ctrlDpressed, {}) # just to flush the ctrl-D press.
  includeScript('www/KeyHandler.js')

if(!require(shinyDebuggingPanel, quietly = T))
  devtools::install_github('professorbeautiful/shinyDebuggingPanel')
require(shinyDebuggingPanel, quietly = T)
observeEvent(input$ctrlDpressed, {}) # just to flush the ctrl-D press.
```

```{r c2}
thisSession <<- shiny::getDefaultReactiveDomain()
output <<- thisSession$output
```
```{r c3}
shinyDebuggingPanel::makeDebuggingPanelOutput(session = thisSession,
  toolsInitialState = TRUE,
   condition='ctrlDpressed === true')
```


```{r withDebuggingPanel, eval=TRUE}

library(shinyjs)

fluidRow(
shinyDebuggingPanel::withDebuggingPanel()
)
```

```{r c4, echo=F}
#shinyUI(
  div(
    title="shinyDebuggingPanel",
    div(h1("A simple example"),
        hr(),
        shinyDebuggingPanel::withDebuggingPanel(),
        h4('To use this facility:'),
        div(style='color:red', strong(em('Toggle ON (and off) the Debugging Panel with control-D.'))),
        pre(
"
Select R or JS for your language, type an expression in the box,
and click the 'evaluate' button.
Use the counter to retrieve previous commands.
"
        ),
        h4('To add this facility to your app:'),
        pre(
"
- install the package with
    install_github('professorbeautiful/shinyDebuggingPanel')
- insert
    require(shinyDebuggingPanel)
into the global code for your app,
- insert
    withDebuggingPanel()
into your UI,
- insert
      makeDebuggingPanelOutput(session, toolsInitialState = TRUE, condition='true')
into your server code.",
            br(),
            pre(
paste("Use the 'condition' arg to set up a toggle for visibility of the panel,
for example driven by pressing a shortcut key.
Look at KeyHandler.js if you want to change from  control-D to a different sequence.
All key responses should be in the same file.
It is in the folder 
", 
system.file('shinyDebuggingPanel', 'www', package='shinyDebuggingPanel')))
        )
    )
  )

```
